/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type SearchFilters struct {
	Instrumenttype []string `json:"Instrumenttype,omitempty"`

	MsType []string `json:"MsType,omitempty"`

	IonMode string `json:"IonMode,omitempty"`

	Contributor []string `json:"Contributor,omitempty"`
}

// AssertSearchFiltersRequired checks if the required fields are not zero-ed
func AssertSearchFiltersRequired(obj SearchFilters) error {
	return nil
}

// AssertRecurseSearchFiltersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SearchFilters (e.g. [][]SearchFilters), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSearchFiltersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSearchFilters, ok := obj.(SearchFilters)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSearchFiltersRequired(aSearchFilters)
	})
}
